### ISSUE TITLE
Need to change routing URL from thankyou page to routing page

### ISSUE THREAD

**Issue by AshutoshJain31** [siddcoool/Aseup-Ts#30]

**Comment by AshutoshJain31** [comment]
Need to redirect listpage form employer page

**Comment by Piyush-Use-Personal** [comment]
Why this is not fixed yet, it should be done last week only. I am frustrated now, please let me know ASAP PLEASESSS!!!!!!

**Comment by Piyush-Use-Personal** [comment]
Why this is not fixed yet, it should be done last week only. I am frustrated now, please let me know ASAP PLEASESSS!!!!!!
